# Site settings
title: "Animal Rationis Capax"
description: "on art, work, and becoming."
lang: "en-US"
timezone: "Europe/Barcelona"  # Updated to your actual location
url: "https://davidglidden.eu"
baseurl: ""
permalink: "/:title/"

# SEO and Social settings
author:
  name: "David Glidden"
  bio: "Violist, teacher, writer. Playing with Jordi Savall. Barcelona."
  email: "d@davidglidden.eu"
  avatar: "/assets/img/avatar.png"

# Social links for SEO
social:
  name: David Glidden
  links:
    - https://instagram.com/quaerendoinvenietis
    - https://davidglidden.eu

# Twitter card settings (even if you don't use Twitter, good for other platforms)
twitter:
  username: davidglidden
  card: summary

# Default SEO image
logo: /assets/img/avatar.png
image: /assets/img/social-default.jpg  # Create this file

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  smart_quotes: ["apos", "apos", "quot", "quot"]

# Pagination (using supported jekyll-paginate)
paginate: 7
paginate_path: "/archive/page:num/"

# Collections
collections:
  posts:
    output: true

# Default front matter
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: false
      image: /assets/img/social-default.jpg  # Default social image
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      image: /assets/img/social-default.jpg

# Plugins - ONLY GitHub Pages supported gems
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

# Jekyll Feed settings
feed:
  title: "Animal Rationis Capax"
  description: "on art, work, and becoming."
  author: "David Glidden"
  path: atom.xml  # or feed.xml if you prefer

# Exclude files from build
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CHANGELOG.md
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache

# Include files in build
include:
  - _redirects
  - .htaccess

# Compress settings
sass:
  style: compressed