# Site settings
title: "Animal Rationis Capax"
description: "on art, work, and becoming."
lang: "en-US"
timezone: "Europe/Paris"
repo: "https://github.com/davidglidden/davidglidden.github.io"
mode: "light" # default theme: "dark" | "light"

# Profile settings
author:
  name: "Animal Rationis Capax" # David F Glidden
  bio: "on art, work, and becoming." # Pilgrim since 1974. Violist.
  username: "davidglidden"
  email: "d@davidglidden.eu"
  avatar: "/assets/img/avatar.png"

# URL settings
url: "https://davidglidden.eu"
baseurl: ""  # must be empty string if site is at root of domain
permalink: "/:title/"  # ensure valid YAML string

# Pagination settings
pagination:
  enabled: true
  per_page: 7
  permalink: '/page:num/'

# Analytics (disable if not in use)
google_analytics: ""  # empty string is safer than undefined
fb_appid: ""

# Collection settings
collections:
  posts:
    output: true

# Markdown and syntax highlighting
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""  # applies to all files
    values:
      layout: "post"
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified: ""
    tags: []
    description: ""
  draft_default_front_matter:
    modified: ""
    tags: []
    description: ""

# Build settings
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sass-converter
  - jekyll-sitemap
  - jekyll-paginate-v2

